forge 'https://forgeapi.puppetlabs.com'

mod 'theforeman-puppet',        '19.2.0'
mod 'puppetlabs-puppetdb',      '8.1.0'
mod 'puppetlabs-postgresql',    '10.3.0'
mod 'puppet-archive',           '7.1.0'
mod 'saz-locales',              '3.2.0'
# mod 'puppetlabs-host_core',     '1.3.0'