---
classes:
  - locales
  - puppet

locales::default_locale: 'en_US.UTF-8'
locales::locales: ['en_US.UTF-8 UTF-8']

puppet::server: false

puppet::agent: true
puppet::agent_server_hostname: 'puppet.local'

puppet::agent_additional_settings:
  include_legacy_facts: true


